.PHONY: FORCE
all: FORCE
	$(MAKE) -C .. zeo_qt test_zeo_qt
clean: FORCE
	$(MAKE) -C .. zeo_qt_clean test_zeo_qt_clean
check: FORCE
	$(MAKE) -C .. test_zeo_qt_check
zeo-qt zeo-qt.exe: FORCE
	 $(MAKE) -C .. zeo_qt
